---
- name: Remove old docker apt repository entries
  ansible.builtin.apt_repository:
    repo: >-
      deb [{{ item }}]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    filename: docker
    update_cache: no
    state: absent
  loop:
    - arch=amd64
    - arch=amd64 signed-by=/usr/share/keyrings/docker.gpg

- name: Remove docker apt signing key from /usr/share/keyrings
  ansible.builtin.file:
    path: /usr/share/keyrings/docker.gpg
    state: absent

- name: Remove docker apt signing key from default apt keyring
  ansible.builtin.apt_key:
    id: "{{ docker_apt_key_fingerprint }}"
    keyring: /etc/apt/trusted.gpg
    state: absent

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add docker apt signing key
  ansible.builtin.apt_key:
    id: "{{ docker_apt_key_fingerprint }}"
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    filename: docker
    update_cache: yes
    state: present

- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Install docker-compose-plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
  when: docker_compose_install | bool

- name: Add docker service overrides directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add docker service overrides
  ansible.builtin.template:
    src: service-overrides.conf
    dest: /etc/systemd/system/docker.service.d/service-overrides.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Create docker configuration directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add docker daemon configuration
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart docker

- name: Start and enable docker
  ansible.builtin.systemd:
    name: docker
    daemon_reload: yes
    masked: no
    enabled: yes
    state: started
